In [55]:
import numpy as np
import pandas as pd
from itertools import product
import matplotlib.pyplot as plt
import scipy as scp
import multiprocessing

In [68]:
df = pd.read_csv("Final_Simulation_Study_3.csv")

In [69]:
df.head()

,Unnamed: 0,Corr,Design,LS2_cov_prob,LS2_length,p_cov_prob,p_length,ts_a_cov_prob,ts_a_length,ts_cov_prob,ts_length,zoom_cov_prob,zoom_length
0,0,Simple,2.0,[[9787 9877 9767 9769 9771]],[[52104.42370326 16453.90091171 4555.36998685...,[[9767 9865 9899 9900 9898]],[[51365.01453006 16245.53710944 5137.22454574...,[[9787 9875 9773 9772 9767]],[[48732.17080497 15426.94800215 4561.27840068...,[[9695 9830 9772 9773 9776]],[[49329.19497865 15645.55150447 4557.06681294...,[[9769 9872 9878 9746 9746]],[[51516.81240562 16273.29141542 4781.43736314...
1,0,Low,2.0,[[9876 9909 9778 9777 9784]],[[52109.87181463 16451.92486163 4555.12022593...,[[9865 9902 9903 9905 9905]],[[51373.3886371 16243.25194071 5137.11014834...,[[9871 9886 9780 9782 9780]],[[50721.23851237 15647.60376626 4557.98862285...,[[9852 9867 9778 9776 9774]],[[50789.51767657 15702.76089581 4555.28817964...,[[9869 9906 9859 9759 9759]],[[51516.82991873 16270.63284238 4779.35824003...
2,0,Med,2.0,[[9873 9889 9777 9761 9768]],[[51008.37743786 16130.10700581 4554.8181885 ...,[[9860 9875 9876 9877 9876]],[[50219.17102343 15881.6474961 5021.97107894...,[[9874 9885 9761 9764 9765]],[[50963.67694836 15891.73695251 4506.36124865...,[[9872 9875 9765 9763 9763]],[[50972.97206877 15904.84270699 4506.9763659 ...,[[9888 9901 9849 9761 9761]],[[51516.58607099 16287.75829007 4789.95093299...
3,0,High,2.0,[[9771 9767 9748 9686 9686]],[[44731.93868204 14145.99506569 4420.41123725...,[[9740 9740 9740 9742 9737]],[[43864.13789811 13867.70472342 4386.04276115...,[[9768 9766 9691 9678 9683]],[[44718.48974304 14140.5151086 4229.32942904...,[[9771 9767 9687 9684 9690]],[[44708.04797238 14140.44851212 4229.16115684...,[[9912 9912 9841 9773 9773]],[[51516.58607099 16290.97492604 4814.94327638...

In [70]:
df_p_cov = pd.DataFrame()
df_ts_cov = pd.DataFrame()
# df_LS1_cov = pd.DataFrame()
df_LS2_cov = pd.DataFrame()
df_zoom_cov = pd.DataFrame()

df_p_len = pd.DataFrame()
df_ts_len = pd.DataFrame()
# df_LS1_len = pd.DataFrame()
df_LS2_len = pd.DataFrame()
df_zoom_len = pd.DataFrame()

for i in range(5):
    
    df_p_cov["cov_prob" + str(10 ** i)] = np.array([df["p_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["p_cov_prob"]))]).astype("float") / 10000
    df_ts_cov["cov_prob" + str(10 ** i)] = np.array([df["ts_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["ts_cov_prob"]))]).astype("float") / 10000
    # df_LS1_cov["cov_prob" + str(10 ** i)] = np.array([df["LS1_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["LS1_cov_prob"]))]).astype("float") / 10000
    df_LS2_cov["cov_prob" + str(10 ** i)] = np.array([df["LS2_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["LS2_cov_prob"]))]).astype("float") / 10000
    df_zoom_cov["cov_prob" + str(10 ** i)] = np.array([df["zoom_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["zoom_cov_prob"]))]).astype("float") / 10000
    
    df_p_len["length" + str(10 ** i)] = np.array([(" ".join(df["p_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["p_length"]))]).astype("float") / 10000
    df_ts_len["length" + str(10 ** i)] = np.array([(" ".join(df["ts_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["ts_length"]))]).astype("float") / 10000
    # df_LS1_len["length" + str(10 ** i)] = np.array([(" ".join(df["LS1_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["LS1_length"]))]).astype("float") / 10000
    df_LS2_len["length" + str(10 ** i)] = np.array([(" ".join(df["LS2_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["LS2_length"]))]).astype("float") / 10000
    df_zoom_len["length" + str(10 ** i)] = np.array([(" ".join(df["zoom_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["zoom_length"]))]).astype("float") / 10000
    
df_p_cov["Design"] = df["Design"]
df_ts_cov["Design"] = df["Design"]
# df_LS1_cov["Design"] = df["Design"]
df_LS2_cov["Design"] = df["Design"]
df_zoom_cov["Design"] = df["Design"]

df_p_len["Design"] = df["Design"]
df_ts_len["Design"] = df["Design"]
# df_LS1_len["Design"] = df["Design"]
df_LS2_len["Design"] = df["Design"]
df_zoom_len["Design"] = df["Design"]

df_p_cov["Corr"] = df["Corr"]
df_ts_cov["Corr"] = df["Corr"]
# df_LS1_cov["Corr"] = df["Corr"]
df_LS2_cov["Corr"] = df["Corr"]
df_zoom_cov["Corr"] = df["Corr"]

df_p_len["Corr"] = df["Corr"]
df_ts_len["Corr"] = df["Corr"]
# df_LS1_len["Corr"] = df["Corr"]
df_LS2_len["Corr"] = df["Corr"]
df_zoom_len["Corr"] = df["Corr"]

df_p_cov["CI"] = "P"
df_ts_cov["CI"] = "TS"
# df_LS1_cov["CI"] = "LS1"
df_LS2_cov["CI"] = "LS2"
df_zoom_cov["CI"] = "zoom"

df_p_len["CI"] = "P"
df_ts_len["CI"] = "TS"
# df_LS1_len["CI"] = "LS1"
df_LS2_len["CI"] = "LS2"
df_zoom_len["CI"] = "zoom"

In [71]:
df_cov_p = pd.concat([df_p_cov, df_ts_cov, df_LS2_cov, df_zoom_cov])
df_cov_p["idx"] = df_cov_p.index
df_cov_p = df_cov_p.sort_values(["idx", "CI"])

df_len = pd.concat([df_p_len, df_ts_len, df_LS2_len, df_zoom_len])
df_len["idx"] = df_len.index
df_len = df_len.sort_values(["idx", "CI"])

In [72]:
df_cov_p

,cov_prob1,cov_prob10,cov_prob100,cov_prob1000,cov_prob10000,Design,Corr,CI,idx
0,0.9787,0.9877,0.9767,0.9769,0.9771,2.0,Simple,LS2,0
0,0.9767,0.9865,0.9899,0.9900,0.9898,2.0,Simple,P,0
0,0.9695,0.9830,0.9772,0.9773,0.9776,2.0,Simple,TS,0
0,0.9769,0.9872,0.9878,0.9746,0.9746,2.0,Simple,zoom,0
1,0.9876,0.9909,0.9778,0.9777,0.9784,2.0,Low,LS2,1
1,0.9865,0.9902,0.9903,0.9905,0.9905,2.0,Low,P,1
1,0.9852,0.9867,0.9778,0.9776,0.9774,2.0,Low,TS,1
1,0.9869,0.9906,0.9859,0.9759,0.9759,2.0,Low,zoom,1
2,0.9873,0.9889,0.9777,0.9761,0.9768,2.0,Med,LS2,2
2,0.9860,0.9875,0.9876,0.9877,0.9876,2.0,Med,P,2
2,0.9872,0.9875,0.9765,0.9763,0.9763,2.0,Med,TS,2
2,0.9888,0.9901,0.9849,0.9761,0.9761,2.0,Med,zoom,2
3,0.9771,0.9767,0.9748,0.9686,0.9686,2.0,High,LS2,3
3,0.9740,0.9740,0.9740,0.9742,0.9737,2.0,High,P,3
3,0.9771,0.9767,0.9687,0.9684,0.9690,2.0,High,TS,3
3,0.9912,0.9912,0.9841,0.9773,0.9773,2.0,High,zoom,3

In [73]:
df_cov_p.to_csv("Final_Simulations_Coverage_Probability_3.csv")
df_len.to_csv("Final_Simulations_Length_3.csv")