In [1]:
import numpy as np
import pandas as pd
from itertools import product
import matplotlib.pyplot as plt
import scipy as scp
import multiprocessing

/Users/andpetrouzeniou/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv("Final_Simulation_Study.csv")

In [3]:
df.head()

,Unnamed: 0,Corr,Design,LS2_cov_prob,LS2_length,p_cov_prob,p_length,ts_a_cov_prob,ts_a_length,ts_cov_prob,ts_length,zoom_cov_prob,zoom_length
0,0,Simple,1.0,[[9791 9795 9709 9553 9553]],[[52051.91332823 15428.85982031 4514.23704326...,[[9776 9894 9908 9914 9917]],[[51367.86518216 16244.73672048 5137.03494103...,[[9783 9796 9646 9543 9554]],[[46193.36010398 14158.34131401 4259.3346664 ...,[[9649 9718 9657 9548 9554]],[[48144.02358799 14449.00917494 4294.01118652...,[[9785 9895 9769 9505 9493]],[[51527.40223511 15689.76357269 4483.63443657...
1,0,Low,1.0,[[9897 9863 9739 9533 9534]],[[52043.10884398 15446.7914142 4513.75321282...,[[9887 9908 9894 9889 9887]],[[51370.85665263 16243.74589641 5136.98342218...,[[9858 9791 9653 9529 9540]],[[48416.33522744 14348.29881689 4255.5175367 ...,[[9820 9769 9656 9538 9539]],[[48851.72782412 14407.08024998 4264.54365598...,[[9890 9903 9747 9512 9482]],[[51526.09436658 15693.0632977 4483.84581129...
2,0,Med,1.0,[[9889 9883 9749 9552 9547]],[[51013.32438459 16067.6393777 4508.07357262...,[[9877 9870 9877 9875 9875]],[[50218.42386681 15879.91119381 5022.46077646...,[[9884 9806 9708 9540 9543]],[[50481.37240976 14827.41032706 4378.31447384...,[[9875 9806 9701 9541 9542]],[[50508.29035794 14841.02117866 4384.47735229...,[[9900 9875 9746 9523 9484]],[[51517.52051301 15713.40404208 4498.40064851...
3,0,High,1.0,[[9768 9766 9678 9609 9562]],[[44729.72980506 14148.69629345 4229.87771361...,[[9739 9729 9732 9731 9728]],[[43855.27016152 13868.30889799 4385.36240258...,[[9762 9721 9675 9573 9566]],[[44710.60057174 13737.80286923 4228.54307698...,[[9774 9724 9682 9577 9566]],[[44708.24977444 13740.49966546 4229.88092287...,[[9913 9881 9776 9566 9524]],[[51516.58607099 15717.60821102 4515.18443301...
4,0,Simple,2.0,[[9799 9768 9794 9764 9623]],[[55989.63051354 16389.16462883 4974.05282463...,[[9839 9893 9932 9955 9953]],[[55988.28215658 17703.69373712 5598.55613506...,[[9825 9780 9803 9719 9548]],[[46764.17210529 14281.05078286 4448.88978543...,[[9675 9652 9687 9696 9597]],[[51663.9179261 15094.38642984 4610.69791898...,[[9845 9891 9854 9846 9706]],[[56174.43385139 17031.87774334 5039.41228324...

In [6]:
df_p_cov = pd.DataFrame()
df_ts_cov = pd.DataFrame()
# df_LS1_cov = pd.DataFrame()
df_LS2_cov = pd.DataFrame()
df_zoom_cov = pd.DataFrame()

df_p_len = pd.DataFrame()
df_ts_len = pd.DataFrame()
# df_LS1_len = pd.DataFrame()
df_LS2_len = pd.DataFrame()
df_zoom_len = pd.DataFrame()

for i in range(5):
    
    df_p_cov["cov_prob" + str(10 ** i)] = np.array([df["p_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["p_cov_prob"]))]).astype("float") / 10000
    df_ts_cov["cov_prob" + str(10 ** i)] = np.array([df["ts_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["ts_cov_prob"]))]).astype("float") / 10000
    # df_LS1_cov["cov_prob" + str(10 ** i)] = np.array([df["LS1_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["LS1_cov_prob"]))]).astype("float") / 10000
    df_LS2_cov["cov_prob" + str(10 ** i)] = np.array([df["LS2_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["LS2_cov_prob"]))]).astype("float") / 10000
    df_zoom_cov["cov_prob" + str(10 ** i)] = np.array([df["zoom_cov_prob"].iloc[j].replace("[", "").replace("]", "").split(" ")[i] for j in range(len(df["zoom_cov_prob"]))]).astype("float") / 10000
    
    df_p_len["length" + str(10 ** i)] = np.array([(" ".join(df["p_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["p_length"]))]).astype("float") / 10000
    df_ts_len["length" + str(10 ** i)] = np.array([(" ".join(df["ts_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["ts_length"]))]).astype("float") / 10000
    # df_LS1_len["length" + str(10 ** i)] = np.array([(" ".join(df["LS1_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["LS1_length"]))]).astype("float") / 10000
    df_LS2_len["length" + str(10 ** i)] = np.array([(" ".join(df["LS2_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["LS2_length"]))]).astype("float") / 10000
    df_zoom_len["length" + str(10 ** i)] = np.array([(" ".join(df["zoom_length"].iloc[j].replace("[", "").replace("]", "").split())).split(" ")[i] for j in range(len(df["zoom_length"]))]).astype("float") / 10000
    
df_p_cov["Design"] = df["Design"]
df_ts_cov["Design"] = df["Design"]
# df_LS1_cov["Design"] = df["Design"]
df_LS2_cov["Design"] = df["Design"]
df_zoom_cov["Design"] = df["Design"]

df_p_len["Design"] = df["Design"]
df_ts_len["Design"] = df["Design"]
# df_LS1_len["Design"] = df["Design"]
df_LS2_len["Design"] = df["Design"]
df_zoom_len["Design"] = df["Design"]

df_p_cov["Corr"] = df["Corr"]
df_ts_cov["Corr"] = df["Corr"]
# df_LS1_cov["Corr"] = df["Corr"]
df_LS2_cov["Corr"] = df["Corr"]
df_zoom_cov["Corr"] = df["Corr"]

df_p_len["Corr"] = df["Corr"]
df_ts_len["Corr"] = df["Corr"]
# df_LS1_len["Corr"] = df["Corr"]
df_LS2_len["Corr"] = df["Corr"]
df_zoom_len["Corr"] = df["Corr"]

df_p_cov["CI"] = "P"
df_ts_cov["CI"] = "TS"
# df_LS1_cov["CI"] = "LS1"
df_LS2_cov["CI"] = "LS2"
df_zoom_cov["CI"] = "zoom"

df_p_len["CI"] = "P"
df_ts_len["CI"] = "TS"
# df_LS1_len["CI"] = "LS1"
df_LS2_len["CI"] = "LS2"
df_zoom_len["CI"] = "zoom"

In [7]:
df_cov_p = pd.concat([df_p_cov, df_ts_cov, df_LS1_cov, df_LS2_cov, df_zoom_cov])
df_cov_p["idx"] = df_cov_p.index
df_cov_p = df_cov_p.sort_values(["idx", "CI"])

df_len = pd.concat([df_p_len, df_ts_len, df_LS1_len, df_LS2_len, df_zoom_len])
df_len["idx"] = df_len.index
df_len = df_len.sort_values(["idx", "CI"])

In [8]:
df_cov_p

,cov_prob1,cov_prob10,cov_prob100,cov_prob1000,cov_prob10000,Design,Corr,CI,idx
0,0.9791,0.9795,0.9709,0.9553,0.9553,1.0,Simple,LS2,0
0,0.9776,0.9894,0.9908,0.9914,0.9917,1.0,Simple,P,0
0,0.9649,0.9718,0.9657,0.9548,0.9554,1.0,Simple,TS,0
0,0.9785,0.9895,0.9769,0.9505,0.9493,1.0,Simple,zoom,0
1,0.9897,0.9863,0.9739,0.9533,0.9534,1.0,Low,LS2,1
...,...,...,...,...,...,...,...,...,...
23,0.9885,0.9885,0.9845,0.9803,0.9803,6.0,High,zoom,23
24,0.9799,0.9813,0.9792,0.9798,0.9794,7.0,Simple,LS2,24
24,0.9783,0.9821,0.9816,0.9820,0.9818,7.0,Simple,P,24
24,0.9660,0.9679,0.9649,0.9653,0.9647,7.0,Simple,TS,24
24,0.9786,0.9825,0.9785,0.9775,0.9775,7.0,Simple,zoom,24

In [9]:
df_cov_p.to_csv("Final_Simulations_Coverage_Probability.csv")
df_len.to_csv("Final_Simulations_Length.csv")